## Add the following vars to Bitbucket pipeline variables for this to work:
## CodeCommitRepoName: The name of the repo in CodeCommit

clone:
  depth: 1

definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        image:
          name: 811583718322.dkr.ecr.ap-southeast-2.amazonaws.com/dotnet-sq:latest
          aws: 
            access-key: $ECR_ACCESS_KEY
            secret-key: $ECR_SECRET_KEY
        caches:
          - dotnetcore           # See https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html
        script:
          - dotnet tool restore
          - dotnet sonarscanner begin /k:"ShopGoDev_SettingsAPI" /d:"sonar.login=${SONAR_TOKEN}" /o:"shopgodev" /v:"${BITBUCKET_COMMIT}" /d:"sonar.host.url=https://sonarcloud.io" /d:sonar.qualitygate.wait="true" /d:sonar.coverageReportPaths="./sonarqubecoverage/SonarQube.xml"
          - dotnet restore SettingsAPI.sln
          - dotnet build SettingsAPI.sln
          - dotnet test --collect:"XPlat Code Coverage" SettingsAPI.sln
          - reportgenerator "-reports:SettingsAPI.Tests/TestResults/*/coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
          - dotnet sonarscanner end /d:"sonar.login=${SONAR_TOKEN}"
          - pipe: sonarsource/sonarqube-quality-gate:1.0.0
            variables:
              SONAR_TOKEN: ${SONAR_TOKEN}
              REPORT_FILE: '.sonarqube/out/.sonar/report-task.txt'


pipelines:
  pull-requests:
    '**':
      - step: *build-test-sonarcloud

   