
version: 0.2

phases:
  install:
      runtime-versions:
          dotnet: 3.1
  build:
      commands:
        - sh build.sh --target=Package
  post_build:
    commands:
      - aws cloudformation package
         --template-file template.yaml
         --s3-bucket ${BUILD_ARTIFACT_BUCKET}
         --output-template-file packaged.yaml
artifacts:
  type: zip
  files:
    - packaged.yaml